### ISSUE TITLE
Cannot list tables

### ISSUE THREAD

**Issue by sereyn** [mlaanderson/database-js#23]
I'm currently working with xlsx tables and I need a query like "SHOW TABLES".  
I did not find it, is there a particular reason?

**Comment by mlaanderson** [comment]
Sorry about the late reply. This needs to be moved to the database-js-xlsx project, which is also one of mine. 

I'd have to dig in more to be sure, but it may be possible to add it with a custom select statement. However, it's not there right now because I didn't need it. If you have an interest please take a look at the code.
