### ISSUE TITLE
There is an issue with the string connection

### ISSUE THREAD

**Issue by javierfuentesm** [mlaanderson/database-js#31]
I think there is an error using a string connection , I had to change my password in order to make it work

for example my password : gwW^/0/L

was not working 
![image](https://user-images.githubusercontent.com/19244527/147782033-e0853930-c624-4894-aaa2-e96cc6a22467.png)

I think it would be cool if you could receive an object so in that way the regex  wont fail and it would be easier to pass the parameters

**Comment by thiagodp** [comment]
Hello, @javierfuentesm !
The library also [allows to use an object](https://github.com/mlaanderson/database-js/blob/f172c8e784688a620ce6f7739173879d68706e09/index.d.ts#L65) with the following properties (instead of the string argument):
- `driverName`
- `username`
- `password`
- `hostname`
- `port`
- `database`
- `parameters`

Sorry that it's not well documented.

**Comment by javierfuentesm** [comment]
Oh thanks , I didn't know good to know, also thanks for the awesome work !
